# Default settings for all clients.  These values are the default
# values, so uncomment and change them if you want different ones.
[DEFAULT]

# How long until a client is disabled and not be allowed to get the
# data this server holds.
# (RFC 3339 duration syntax)
timeout = PT60S

# How often to run the checker to confirm that a client is still up.
# Note: a new checker will not be started if an old one is still
# running.  The server will wait for a checker to complete until the
# above "timeout" occurs, at which time the client will be disabled,
# and any running checker killed.
# (RFC 3339 duration syntax)
interval = PT5S

# Extended timeout is an added timeout that is given once after a
# password has been sent sucessfully to a client.  This allows for
# additional delays caused by file system checks and quota checks.
# (RFC 3339 duration syntax)
extended_timeout = PT2M

# What command to run as "the checker".
# if file /tmp/<hostname> exists, check succeeds
checker = /usr/bin/cat /tmp/%%(host)s

# Whether to approve a client by default after the approval delay.
approved_by_default = False

# Whether this client is enabled by default
enabled = False

[client0]
host = mandos-client
key_id = 83144bacc1af197533bc02a3ffc6eeeac104f95d5bd96eabd595f4b05db304b7
fingerprint = C35E2119651F323B633874F1E0EEDA918822F0F5
secret =
    hQIMA1iHUq2pWIzhARAAjCqulPFBvJv4DTcQO1v+2Lk7sVS+GtOoSDbyKy73+d2A
    oTQCN5LHC+xNSqk4Jdb5Ug8mmsMUCf477K5T1wRyxmS0ruKVGXCsRNAjkO0Tjdjp
    74dlZlVa0tNd3iXDlPM1JANFRr9mKRw35oMly+ZdzsrMav0a4YDOWeqQob69DI+M
    00sG6OjsJxlmWmqb2yRBSCqZc9k93KjHi8A+X+JtmVttKLqeTV8mHwbMKdm/34oO
    XGEJA7aMQ0QSYxn+prBtBlF1nUhjZe+/yv/mSGgcj2aPfw7zIkonXo1q3AKw8xTY
    Vrgwas76l+3VoA2ncCM7VapN0P3jPWm0pcbN+5Vz7yornd21MPG+vBsVQmnakdvW
    Q9kN8FDKqh1iRJgNGPeyXit9V5VitW0fusaIc1sQigcTKmAQtxUA55A59upDa4D/
    z0hAb/sFAxK4noX+4WTcqm+X0RZUBhcGovPab0nEQPctXs4ZcCkhD6ziMb/Dp7mW
    ccGQUnOE1ncL74krk2XlQB40NfB3x2In00Jf0WcKfcEH9jGqKW19l8gqUNfEyUdP
    TB40T57xY2dYVFB2JNJPsEhQXZB5l4kRNiYC0u7iSSrcxDpPdmhCwLyeQBhbUYfr
    Yos75Rl6VGHKXOIy8vLvVufGk9kVUXqlQKCToMGJJsHNDipaVSRWl1hbp3zU7Z/S
    6QGPDo2R7DVeqLiA4E7DeapAGlq5pJaBg5TlQr80RQUgfp7JNAUV98BUoeHMr/AC
    hB1VI09LlkRGBXnaHVQfI6Fwwlisx9wu96wHavfcddBUCH+Yn77jImyDcQbipxlW
    aAee4b0FHGliRNVQ+dAYvv4EYpGIpcea2NBP7d11Ox4Out/PhYq4LxHZRUqPdxkh
    cNY6+OoE3ghw+T15vaVuUhRJuzLEgTL8TPEG+E6rtG5PAOGEedlg3iUWmXRCdJku
    FH9zv9jZ8IjoAks9zJ9ZlIjeFSzd217cSJILYtU6E7kPY6pEtSqZ6OLBAa3YyHc/
    AvjyU9M9CozsCg7+M4sUuk+wwN19qlHMM+WvW3dO1dvjy2cp1BClvO5dAgsyb16v
    S6Nsrg/GjlN1ECdR4G5a7UFHsW0MRlXxwWn4sfaGahDzKyDSCcWTtlj3rN3hBHI8
    y3988t4+UZGwfFfPLujgpBWmwb6i2+zVn+3ib1z2P3l3JolIg/WVxTXzRdAlv+wQ
    3W4B4EkAfF+gDk36ZlFVSYX5c26YSg+wDxWopOYo0LMH4wxHSE7E6kprk5sbYyPX
    HRezQWS7U1o/3/1t4I4UAP1E4Cccox24LiYkVm58qaCLbHiouRSNRdTYtg9Y2Gby
    SktfHbg7K40M6xpaHC5VL9Qd0CNkY7maCjqaZGPo/E+Oh7sYekC0hPfjZbWeCHy+
    vvxqDCL//GnlOZ7nbn2kpwCl2kg3IavBN3kxZuDjAhskiYd1Xe2q1YpzWt7yYawH
    4lAxCdN6iyIcwAqn+NQVAsVzXj9XfVSOaUWIhj4Y5zqXCb54T8KaVDsdpdxlUzbX
    K9JEgUXq4BYwwbWyS29HPLwNzjz1NUhdrQ==